EVENTCLOSED = "The event is closed and cannot be modified"
EVENTIMMUTABLE = "Events are immutable and thus cannot be modified"
EVENTSEQIMMUTABLE = "Events sequences are immutable and thus cannot be modified"
ISDUPLICATE = "The event sequence cannot contain duplicates"
KEYWORDNOTEXIST = "The provided keyword does not exist"